plugins {
    id 'java'
    alias(libs.plugins.spring.framework)
    alias(libs.plugins.spring.dependencyManagement)
    alias(libs.plugins.catalogUpdater)
    alias(libs.plugins.reckon)
    alias(libs.plugins.sentry)
}

group = 'fr.anisekai'

apply from: 'gradle/reckon.gradle'
apply from: 'gradle/java.gradle'

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation(libs.bundles.spring)
    testImplementation(libs.testing.springframework.test)
    testImplementation(libs.testing.h2)
    testImplementation(libs.testing.springframework.data.jpa.test)

    implementation(libs.security.uuid)
    runtimeOnly(libs.database.mariadb.client)

    implementation(libs.bundles.anisekai)
    implementation(libs.bundles.discord)
    implementation(libs.bundles.flyway)
    implementation(libs.bundles.jwt)
    implementation(libs.bundles.utils)

    annotationProcessor(libs.dev.spring.configuration.processor)
    implementation(libs.dev.annotations.jetbrains)
}

test {
    useJUnitPlatform()
}

sentry {
    includeSourceContext = true

    org = 'anisekai'
    projectName = 'service'
    authToken = providers.gradleProperty('sentry.authToken')
            .orElse(providers.environmentVariable('SENTRY_AUTH_TOKEN'))
            .getOrNull()
}

// Thanks, Sentry (pls fix your plugin idk)
tasks.named('sourcesJar') {
    dependsOn('generateSentryDebugMetaPropertiesjava')
    dependsOn('collectExternalDependenciesForSentry')
}

tasks.matching { it.name.contains("sentry") || it.name.contains("Sentry") }.configureEach {
    mustRunAfter('generateJava')
}